Feature paypal redirect
accidentalshakespeare/company-site pull request #80
Opened 2017-03-24 22:10 UTC by PatrickJamesHoban

Updated redirect links for paypal one-time donation so that if donation is made paypal will redirect back to thank you page and if user cancels out of donation, they will be taken back to the site donate page.

![image](https://cloud.githubusercontent.com/assets/22061432/24315236/233cc0de-10a3-11e7-9d58-6133537de902.png)

![image](https://cloud.githubusercontent.com/assets/22061432/24315247/35d9a77a-10a3-11e7-9ced-196e0f094614.png)

I also updated the upcoming page as I noticed some of the code had been overwritten to a seemingly older version.  The update allows for the brown paper ticket link to appear on the upcoming event automatically when the user adds the ticket code to the md file.

Without code in md file...
![image](https://cloud.githubusercontent.com/assets/22061432/24315323/a1a189a0-10a3-11e7-8735-00ad1426b91a.png)

This is the update in the code for the upcoming.html...
![image](https://cloud.githubusercontent.com/assets/22061432/24315372/da6ba84c-10a3-11e7-8925-44d8b26c1acb.png)

Here is where the user would add the code in the md file...
![image](https://cloud.githubusercontent.com/assets/22061432/24315357/c79a824c-10a3-11e7-8717-9cdb06251856.png)

Here is what the site would look like after code is added in md file...
![image](https://cloud.githubusercontent.com/assets/22061432/24315306/8b799924-10a3-11e7-9ff1-4f5fa49a74e5.png)

2017-04-02 20:36 UTC, hollabaq86 requested changes

2017-04-02 20:36 UTC, hollabaq86 commented on _includes/upcoming.html
> +  <!-- PH 3/24/17 - The below needs to be nested under site.upcoming as it is now -->
these comments are visible in inspector, we may want to move to README or instructions.txt file

2017-04-02 20:36 UTC, hollabaq86 commented on _includes/upcoming.html
> +      <A HREF="http://www.brownpapertickets.com/event/{{ tickets.code }}"><IMG SRC="http://www.brownpapertickets.com/g/6/BPT_buy_tickets_small.png" WIDTH=108px HEIGHT=58px BORDER=0></A>
tags and attributes are in all caps... can we change back to lowercase to match all styles?

2017-04-02 20:36 UTC, hollabaq86 commented on donate.html
> +          <!-- PH 3/24/17 - Adding the return links back to site following paypal donation -->
appreciate adding this comment, but it's not needed. Please remove

2017-04-03 21:21 UTC, PatrickJamesHoban commented
@hollabaq86 - Hey Holly, Finally got around to making those few small tweaks you requested.  I pulled the latest master, merged into the feature branch on my machine, made those three edits you asked for, I double checked everything still worked on my localhost and then pushed the feature back up again.  This pull request is now reflective of those changes and ready for merge.  Let me know if you have questions or need anything else!  ~PH

2017-04-05 22:03 UTC, hollabaq86 approved these changes

2017-04-05 22:03 UTC, merged